# Generated by Django 4.2.1 on 2023-05-04 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureETIMDetails',
            fields=[
                ('id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('featureCode', models.TextField(db_index=True, verbose_name='Код ETIM')),
                ('featureUom', models.TextField(blank=True, null=True, verbose_name='ЕИ характеристики ETIM')),
                ('featureName', models.TextField(blank=True, null=True, verbose_name='Наименование характеристики ETIM')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_hit', models.BooleanField(default=False, null=True, verbose_name='Хит!')),
                ('is_new', models.BooleanField(default=False, null=True, verbose_name='Новое!')),
                ('show', models.BooleanField(blank=True, default=True, verbose_name='Показывать на сайте')),
                ('discount', models.IntegerField(default=0, null=True, verbose_name='Скидка процент')),
                ('delete', models.BooleanField(default=False)),
                ('dimension', models.JSONField(blank=True, null=True, verbose_name='Единица измерения')),
                ('EAN', models.JSONField(blank=True, null=True, verbose_name='EAN товара (Штрих-код)')),
                ('GuaranteePeriod', models.CharField(max_length=100, verbose_name='Гарантийный срок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='staticfiles/img/product/main', verbose_name='Фото (Основное)')),
                ('ItemID', models.BigIntegerField(blank=True, verbose_name='ID позиции')),
                ('ItemsPerUnit', models.BigIntegerField(blank=True, verbose_name='Кол-во штук в упаковке')),
                ('Multiplicity', models.BigIntegerField(blank=True, verbose_name='Кратность закупки у поставщика')),
                ('ParentProdCode', models.CharField(blank=True, max_length=50, verbose_name='ID категории товара')),
                ('ParentProdGroup', models.CharField(blank=True, max_length=255, verbose_name='Название категории товара')),
                ('ProductCode', models.CharField(blank=True, max_length=255, verbose_name='ProductCode')),
                ('ProductDescription', models.TextField(blank=True, verbose_name='ProductDescription')),
                ('ProductGroup', models.TextField(blank=True, null=True, verbose_name='Товарная группа (Категория каталога)')),
                ('ProductName', models.TextField(blank=True, db_index=True, null=True, verbose_name='ProductName')),
                ('ReceiverPrdCode', models.TextField(blank=True, null=True, verbose_name='ReceiverPrdCode')),
                ('SenderPrdCode', models.BigIntegerField(blank=True, null=True, verbose_name='Код товара в УС отправителя')),
                ('UOM', models.CharField(blank=True, max_length=3, verbose_name='UOM')),
                ('VendorProdNum', models.TextField(blank=True, null=True, verbose_name='Артикул')),
                ('Weight', models.FloatField(blank=True, null=True, verbose_name='Вес')),
                ('Series', models.TextField(blank=True, null=True, verbose_name='Серия')),
                ('AnalitCat', models.CharField(blank=True, max_length=3)),
                ('QTY', models.BigIntegerField(blank=True, null=True)),
                ('SumQTY', models.BigIntegerField(blank=True, null=True)),
                ('Price2', models.BigIntegerField(blank=True, null=True)),
                ('RetailPrice', models.BigIntegerField(blank=True, null=True)),
                ('RetailCurrency', models.CharField(blank=True, max_length=50)),
                ('CustPrice', models.BigIntegerField(blank=True, null=True)),
                ('MRC', models.BigIntegerField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
            ],
        ),
        migrations.CreateModel(
            name='RsCatalog',
            fields=[
                ('id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Level2ID', models.BigIntegerField(verbose_name='ID второго уровня РС каталога ')),
                ('Level2Name', models.TextField(verbose_name='Описание второго уровня РС каталога')),
                ('Level3ID', models.BigIntegerField(verbose_name='ID третьего уровня РС каталога')),
                ('Level3Name', models.TextField(verbose_name='Описание третьего уровня РС каталога')),
                ('Level4ID', models.BigIntegerField(verbose_name='ID четвертого уровня РС каталога')),
                ('Level4Name', models.TextField(verbose_name='Описание четвертого уровня РС каталога')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedProd',
            fields=[
                ('id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('service', models.TextField(verbose_name='ID сопутствующего товаров')),
                ('relatedProd_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_video',
            fields=[
                ('id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('show', models.BooleanField(blank=True, default=False)),
                ('video_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_image',
            fields=[
                ('id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='staticfiles/img/product')),
                ('show', models.BooleanField(blank=True, default=False)),
                ('image_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('service', models.TextField(verbose_name='Passport')),
                ('passport_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureETIMDetails_Data',
            fields=[
                ('id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('featureValue', models.TextField(blank=True, verbose_name='Значение характеристики ETIM')),
                ('featureETIMDetails_index', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite_product',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('count', models.IntegerField(blank=True, default=1, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('service', models.TextField(verbose_name='страна производитель')),
                ('country_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateInfo',
            fields=[
                ('id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('service', models.TextField(blank=True, verbose_name='URL сертификата сертификата')),
                ('certificate_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Analog',
            fields=[
                ('id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('service', models.TextField(verbose_name='Код замены позиции в кодах Русского Света')),
                ('analog_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
