# Generated by Django 4.2.1 on 2023-05-04 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_itemid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogBrochure',
            fields=[
                ('id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('data', models.TextField(verbose_name='ссылка')),
                ('brochure_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
