# Generated by Django 4.2.1 on 2023-05-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_catalogbrochure'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_image',
            name='imageURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
