# Generated by Django 4.2.1 on 2023-05-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_image_imageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_video',
            old_name='video',
            new_name='videoURL',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ReceiverPrdCode',
        ),
    ]
