# Generated by Django 4.2.1 on 2023-05-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_video_product_video_videourl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dimension',
            new_name='Dimension',
        ),
    ]
