# Generated by Django 4.2.1 on 2023-05-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_dimension_product_dimension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureetimdetails_data',
            name='featureValue',
            field=models.TextField(blank=True, null=True, verbose_name='Значение характеристики ETIM'),
        ),
    ]
