# Generated by Django 4.2.1 on 2023-05-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_featureetimdetails_index_featureetimdetails_data_featureetimdetails_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='AnalitCat',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='GuaranteePeriod',
            field=models.CharField(max_length=100, null=True, verbose_name='Гарантийный срок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ItemsPerUnit',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Кол-во штук в упаковке'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Multiplicity',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Кратность закупки у поставщика'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ParentProdCode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID категории товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ParentProdGroup',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название категории товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductCode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ProductCode'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductDescription',
            field=models.TextField(blank=True, null=True, verbose_name='ProductDescription'),
        ),
        migrations.AlterField(
            model_name='product',
            name='RetailCurrency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='UOM',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='UOM'),
        ),
    ]
