# Generated by Django 4.2.1 on 2023-05-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_analitcat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='GuaranteePeriod',
            field=models.TextField(null=True, verbose_name='Гарантийный срок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ParentProdGroup',
            field=models.TextField(blank=True, null=True, verbose_name='Название категории товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductCode',
            field=models.TextField(blank=True, null=True, verbose_name='ProductCode'),
        ),
        migrations.AlterField(
            model_name='product',
            name='RetailCurrency',
            field=models.TextField(blank=True, null=True),
        ),
    ]
