# Generated by Django 4.2.1 on 2023-05-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_productname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='Фото (Основное)'),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='imageURL',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_video',
            name='videoURL',
            field=models.TextField(blank=True, null=True),
        ),
    ]
