# Generated by Django 4.2.1 on 2023-05-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_image_alter_product_image_imageurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rscatalog',
            name='Level2ID',
            field=models.BigIntegerField(blank=True, verbose_name='ID второго уровня РС каталога '),
        ),
        migrations.AlterField(
            model_name='rscatalog',
            name='Level2Name',
            field=models.TextField(blank=True, verbose_name='Описание второго уровня РС каталога'),
        ),
        migrations.AlterField(
            model_name='rscatalog',
            name='Level3ID',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID третьего уровня РС каталога'),
        ),
        migrations.AlterField(
            model_name='rscatalog',
            name='Level3Name',
            field=models.TextField(blank=True, null=True, verbose_name='Описание третьего уровня РС каталога'),
        ),
        migrations.AlterField(
            model_name='rscatalog',
            name='Level4ID',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID четвертого уровня РС каталога'),
        ),
        migrations.AlterField(
            model_name='rscatalog',
            name='Level4Name',
            field=models.TextField(blank=True, null=True, verbose_name='Описание четвертого уровня РС каталога'),
        ),
    ]
