# Generated by Django 4.2.1 on 2023-05-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_rscatalog_level2id_alter_rscatalog_level2name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='CustPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='MRC',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='QTY',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='RetailPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='SumQTY',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
