# Generated by Django 4.2.1 on 2023-05-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0017_series_alter_product_series"),
    ]

    operations = [
        migrations.AlterField(
            model_name="series",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
