# Generated by Django 4.2.1 on 2023-05-13 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_series_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_video',
            name='show',
        ),
    ]
