# Generated by Django 4.2.1 on 2023-05-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Скидка цена'),
        ),
    ]
