# Generated by Django 4.2.2 on 2023-06-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='MRC',
        ),
        migrations.AddField(
            model_name='product',
            name='LastUpdDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление'),
        ),
        migrations.AddField(
            model_name='product',
            name='PartnerQTY',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Остатки товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='PartnerUOM',
            field=models.TextField(blank=True, null=True, verbose_name='Единица измерения товара в учетной системе поставщика'),
        ),
        migrations.AlterField(
            model_name='product',
            name='AnalitCat',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Аналитическая категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='CustPrice',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена клиента без НДС '),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price2',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена клиента с НДС'),
        ),
        migrations.AlterField(
            model_name='product',
            name='QTY',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='RetailCurrency',
            field=models.TextField(blank=True, null=True, verbose_name='Рекомендованная валюта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='RetailPrice',
            field=models.FloatField(blank=True, null=True, verbose_name='Базовая цена товара с НДС'),
        ),
        migrations.AlterField(
            model_name='product',
            name='SumQTY',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма ост. на складе РС и складе поставщика'),
        ),
    ]
