# Generated by Django 4.2.2 on 2023-06-14 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_remove_product_mrc_alter_product_lastupddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('service', models.TextField(verbose_name='страна производитель')),
            ],
        ),
        migrations.RemoveField(
            model_name='country',
            name='service',
        ),
        migrations.AddField(
            model_name='country',
            name='countries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.countries'),
        ),
    ]
