# Generated by Django 4.2.2 on 2023-06-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_countries_remove_country_data_country_countries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analog',
            old_name='service',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='catalogbrochure',
            old_name='service',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='certificateinfo',
            old_name='service',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='countries',
            old_name='service',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='passport',
            old_name='service',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='relatedprod',
            old_name='service',
            new_name='data',
        ),
    ]
