# Generated by Django 4.2.2 on 2023-06-24 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_rename_service_analog_data_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='featureetimdetails_data',
            unique_together={('featureETIMDetails_product', 'featureETIMDetails', 'featureValue')},
        ),
    ]
