# Generated by Django 4.2.2 on 2023-06-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_faq_newcall_newpartner_delete_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Politics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('role', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
