# Generated by Django 4.2.1 on 2023-05-04 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('delivery_text', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('order_name', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'CREATED'), (1, 'ON_PAY'), (2, 'Pleasantly'), (3, 'Delivery'), (4, 'SUCCEEDED'), (5, 'FAILED'), (6, 'REFUNDED'), (7, 'Completed')], db_index=True, default=order.models.Status['CREATED'], verbose_name='status')),
                ('data_order', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('chek', models.TextField(verbose_name='Чек')),
                ('pay', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('pay_online', models.BooleanField(blank=True, default=None, null=True, verbose_name='Оплата онлайн')),
                ('sum', models.FloatField(verbose_name='Сумма')),
                ('date_close', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата закрытия')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Скидка')),
                ('count_product', models.IntegerField(blank=True, default=0, null=True, verbose_name='Кол-во продуктов')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.delivery')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_list',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('money', models.FloatField()),
                ('count', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
