# Generated by Django 4.2.1 on 2023-05-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='chek',
            field=models.TextField(blank=True, null=True, verbose_name='Чек'),
        ),
    ]
